language: java
jdk:
- openjdk8
script:
- "./gradlew build --stacktrace"
after_success:
- gradle/deploy_snapshot.sh
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: QfxkQwwG7cGK1qrYZkbe5OYtdxr5GZ/x+fke8rb3YfUOwsS6ajhlxSUYPsgFUIE2vBoJ8SktufEM1wJiSCfXDujBrk6Lk2n9eh2MRxbDKbAti6umGRJycHAOZnX5abNQpIQoEfCKBCPNsuiFSG8CiDOSINCMD0ZIC2RjVKBF4TLq16zc61OTjbGqlv9iZmWfQDy8fTSjAkmb4UVnk5orpJRLOZJ9hfHfuen24KFQoGQ+3l0qjiprNdAIxk5O9gVhPm9dNz69AXIzb/6BZLzvwbIWa4rgVpuY1IFjX/J1mjcprUyRQTgZuIf+VFiJsY1KEJWXiTMhMuCqsC67uWqoqgZ7oWCevYpWAt0m7Fx6xPLtjOlSvan+A5LzwSUv/sNZW1rVH4vSMAl5nmCWp0z/HKIMQhWMKcqzSIaAA+AkqquJvK0o82jWapiheTFx1XYAaoIaXr+6IIWHmxAemGL0rLZ0qWbtKWB5Vaz5tsEcgOL4b6VuSHpWk9ngAnB0RMD9JZjLZ6hCyzD/32Kr0ITgkIZ6Tfd51Qp31FowTOB4ATcgG/wDueej4/SZxkhJXqwIU5DpIaDB5RecYmKOXUbbLsW7WzloftSm0QV+aWCFl0/BxfljfvXOmHnSi6D9X+N7mIIrMtsGvM5vDTjkFOMN8SBBWJEGsRWcTA/KN9b+gL8=
  - secure: j5o8tjP1/RiShw1iLJxWKiqPKtRupA3WbMjKClrVj70a+y5l1bVEUjd8OT474YzfjZRP+pDXs6vQMXRe1zX/+vKw4bKxUOaxCaj7js/oUsHQAW0bKygEYBkRfpBEaz0YEvomGE20jTX1DUPAEX2Md+MV0ny6o0DtM09ETDv+XOdHxmfOpaM6Sgbt4fMuQnp5SBLzr1Po6EutezbpPywwVGUAUbT/q+7I4l549gFy+B89nALrjUF1PxX8r2w4R5gmBNgP/BA4KoOPGreBQQTxOhqBK3Qkr+WwHUnuGTupRSykeesvHsud9mbBFJH0wWz5g5aWInQApqwuOud5yoZcLZx86PZdrXuGHuMkaeTkfSgkSjL3+HWjNm8jEE8ZvMNvBxRoYhstX+e9yhlyQNye9+/1fOZoDoMfJrKjc3FEGXsV+u2dh6/n1jSb/GzmusNRKnogm278pJbjMgrMCJdyK5RWFkF0r9R2zOKz0oCYmrMSmv2eyR6oMsMr+glS/SIcVBgimA0ihMsHI2qX8+WDTTdn0UHremhDtf2GP4huMO66fB0Pwo5iH54E6cB1+8rhvu6mTNrihbSgKCXdzK5SvtrHvhPnpK9i7HsRnEnUhs1RsJf4BEibdDFObTb6HzE2m18duiy2iZU0K+PLSsAhAoW6+q1mlejlKdnlB3Csg8s=
